#docker-compose.yml
version: '3.8'

services:
  # 1. Định nghĩa container cho Database PostgreSQL
  postgres_db:
    image: postgres:16-alpine # Dùng bản Postgres 16 siêu nhẹ
    container_name: medical_postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <-- Điền password DB hiện tại của ông vào đây
      POSTGRES_DB: ${DB_NAME}     # <-- Điền tên Database của ông vào đây
    ports:
      - "5433:5432" # Mở cổng 5432 từ container ra máy thật để Postman/DBearer chọc vào được
    volumes:
      - postgres_data:/var/lib/postgresql/data # Lưu dữ liệu xuống ổ cứng máy thật, tắt container không bị mất data

  # 2. Định nghĩa container cho con App Node.js thuần của mình
  node_app:
    build: . # Bảo Docker tìm file 'Dockerfile' ngay tại thư mục này để tự build Image
    container_name: medical_node_container
    ports:
      - "3000:3000" # Mở cổng 3000 ra ngoài để ông test Postman
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD} # <-- Trùng với password ở trên
      - DB_HOST=${DB_HOST}           # <-- ĐIỂM CHÍ MẠNG: Không dùng 'localhost', phải dùng tên service của DB trong Docker!
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - SECRET=${SECRET}    # <-- Điền mã secret JWT của ông vào đây
    depends_on:
      - postgres_db # Bảo con App đợi con Database khởi động xong xuôi thì mới được chạy

volumes:
  postgres_data: # Khai báo vùng bộ nhớ lưu trữ data cho Postgres